//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stagingclinicEntities1 : DbContext
    {
        public stagingclinicEntities1()
            : base("name=stagingclinicEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<EmailLog> EmailLogs { get; set; }
        public virtual DbSet<MemberDetail> MemberDetails { get; set; }
        public virtual DbSet<Table_Appointment> Table_Appointment { get; set; }
        public virtual DbSet<Table_Appointment_Slot> Table_Appointment_Slot { get; set; }
        public virtual DbSet<Table_Client_Note> Table_Client_Note { get; set; }
        public virtual DbSet<Table_ClientData> Table_ClientData { get; set; }
        public virtual DbSet<Table_Invoice_Info> Table_Invoice_Info { get; set; }
        public virtual DbSet<Table_Invoice_Supplements> Table_Invoice_Supplements { get; set; }
        public virtual DbSet<Table_Supplement> Table_Supplement { get; set; }
        public virtual DbSet<Table_Supplier> Table_Supplier { get; set; }
        public virtual DbSet<Medical_Aid_Details> Medical_Aid_Details { get; set; }
        public virtual DbSet<Next_Of_Kin> Next_Of_Kin { get; set; }
        public virtual DbSet<Table_ArticleKeyword> Table_ArticleKeyword { get; set; }
        public virtual DbSet<Table_BlogPost> Table_BlogPost { get; set; }
        public virtual DbSet<Table_BlogPostKeyword> Table_BlogPostKeyword { get; set; }
        public virtual DbSet<Table_MedicalCertificate> Table_MedicalCertificate { get; set; }
        public virtual DbSet<Table_Prescription> Table_Prescription { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
