//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_Aid_Details
    {
        public int Med_Id { get; set; }
        public string Med_Aid_Name { get; set; }
        public string Med_Aid_No { get; set; }
        public string Med_Option { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<System.DateTime> CaptureDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Table_ClientData Table_ClientData { get; set; }
    }
}
