//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDetail
    {
        public int MemberDetailId { get; set; }
        public string Member_Name { get; set; }
        public string Member_Surname { get; set; }
        public string Member_Residential_Address { get; set; }
        public string Member_Postal_Address { get; set; }
        public string Member_Employer_Name { get; set; }
        public string Member_City { get; set; }
        public string Member_Town { get; set; }
        public string Member_Tel_Home { get; set; }
        public string Member_Tel_Work { get; set; }
        public string Member_Tel_Cell { get; set; }
        public string Member_Email { get; set; }
        public string Member_Occupation { get; set; }
        public string Member_ID_Number { get; set; }
        public Nullable<System.DateTime> CapturedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Code { get; set; }
    
        public virtual Table_ClientData Table_ClientData { get; set; }
    }
}
