//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Next_Of_Kin
    {
        public int Kin_Id { get; set; }
        public string Kin_Name { get; set; }
        public string Kin_Relationship { get; set; }
        public string Kin_HM_Tel_No { get; set; }
        public string Kin_WK_Tel_No { get; set; }
        public string Kin_Cell_Tel_No { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.DateTime> CaptureDate { get; set; }
        public Nullable<int> Client_Id { get; set; }
    
        public virtual Table_ClientData Table_ClientData { get; set; }
    }
}
