//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_BlogPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_BlogPost()
        {
            this.Table_BlogPostKeyword = new HashSet<Table_BlogPostKeyword>();
        }
    
        public int BlogPost_ID { get; set; }
        public string Title { get; set; }
        public byte[] FileData { get; set; }
        public string ContentType { get; set; }
        public string BlogText { get; set; }
        public Nullable<System.DateTime> CapturedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public string CapturedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<int> PostViews { get; set; }
        public string StringParam { get; set; }
        public string Description { get; set; }
        public byte[] ThumbFileData { get; set; }
        public string ThumbContentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_BlogPostKeyword> Table_BlogPostKeyword { get; set; }
    }
}
