//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Client_Note
    {
        public int Client_Note_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public string Note { get; set; }
        public Nullable<int> Appointment_ID { get; set; }
    
        public virtual Table_Appointment Table_Appointment { get; set; }
    }
}
