//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Appointment()
        {
            this.Table_Client_Note = new HashSet<Table_Client_Note>();
        }
    
        public int Appointment_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<double> Appointment_Duration { get; set; }
        public Nullable<int> Appointment_Slot_ID { get; set; }
        public Nullable<bool> IsAppointCancelled { get; set; }
        public Nullable<bool> IsRescheduled { get; set; }
        public string ReasonForCancelling { get; set; }
        public Nullable<System.DateTime> CapturedDatetime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> CurrentPatient { get; set; }
        public string EmailAddress { get; set; }
        public string Contact_Number { get; set; }
        public string Passport_Number { get; set; }
        public string Id_Number { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual Table_Appointment_Slot Table_Appointment_Slot { get; set; }
        public virtual Table_ClientData Table_ClientData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Client_Note> Table_Client_Note { get; set; }
    }
}
