//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Prescription
    {
        public int PrescriptionID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IdentificationCode { get; set; }
        public string PrescriptionNote { get; set; }
        public Nullable<System.DateTime> SignatureDateTime { get; set; }
        public Nullable<System.DateTime> CapturedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual Table_ClientData Table_ClientData { get; set; }
    }
}
