//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Supplier()
        {
            this.Table_Supplement = new HashSet<Table_Supplement>();
        }
    
        public int Supplier_ID { get; set; }
        public string Supplier_Contact_Person { get; set; }
        public string Supplier_Cell { get; set; }
        public string Supplier_Fax { get; set; }
        public string Supplier_Email { get; set; }
        public string Supplier_Bank { get; set; }
        public string Supplier_Branch_Code { get; set; }
        public string Supplier_Account_Number { get; set; }
        public string Supplier_Type_Of_Account { get; set; }
        public string Supplier_Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Supplement> Table_Supplement { get; set; }
    }
}
