//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ClientData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_ClientData()
        {
            this.MemberDetails = new HashSet<MemberDetail>();
            this.Table_Appointment = new HashSet<Table_Appointment>();
            this.Medical_Aid_Details = new HashSet<Medical_Aid_Details>();
            this.Next_Of_Kin = new HashSet<Next_Of_Kin>();
            this.Table_Invoice_Info = new HashSet<Table_Invoice_Info>();
            this.Table_MedicalCertificate = new HashSet<Table_MedicalCertificate>();
            this.Table_Prescription = new HashSet<Table_Prescription>();
        }
    
        public int Client_ClientID { get; set; }
        public string Client_Name { get; set; }
        public string Client_Surname { get; set; }
        public string Client_Address { get; set; }
        public string Client_Street2 { get; set; }
        public string Clientt_Suburb { get; set; }
        public string Client_Town { get; set; }
        public string Client_Province { get; set; }
        public string Client_Country { get; set; }
        public string Client_Tel_Home { get; set; }
        public string Client_Tel_Work { get; set; }
        public string Client_Tel_Cell { get; set; }
        public string Client_Email { get; set; }
        public string Client_Reference { get; set; }
        public string Client_ID_Number { get; set; }
        public Nullable<System.DateTime> Client_Date_Of_birth { get; set; }
        public Nullable<System.DateTime> CapturedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> BMI_Reading { get; set; }
        public string Dep_Code { get; set; }
        public string Employer_Name { get; set; }
        public string Title { get; set; }
        public Nullable<int> Age { get; set; }
        public string PassportNumber { get; set; }
        public string Createdby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberDetail> MemberDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Appointment> Table_Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_Aid_Details> Medical_Aid_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Next_Of_Kin> Next_Of_Kin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Invoice_Info> Table_Invoice_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_MedicalCertificate> Table_MedicalCertificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Prescription> Table_Prescription { get; set; }
    }
}
