//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Invoice_Supplements
    {
        public int Invoice_Supplements_ID { get; set; }
        public Nullable<int> Invoice_Info_ID { get; set; }
        public Nullable<int> Supplement_ID { get; set; }
        public Nullable<double> Invoice_Supplements_Price { get; set; }
        public Nullable<int> Invoice_Supplements_Quantity { get; set; }
        public string Invoice_Supplements_TotalPrice { get; set; }
        public Nullable<System.DateTime> CapturedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual Table_Invoice_Info Table_Invoice_Info { get; set; }
        public virtual Table_Supplement Table_Supplement { get; set; }
    }
}
