//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Supplement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Supplement()
        {
            this.Table_Invoice_Supplements = new HashSet<Table_Invoice_Supplements>();
        }
    
        public int Supplement_ID { get; set; }
        public string Supplement_Description { get; set; }
        public Nullable<double> Supplement_Cost_Excl { get; set; }
        public Nullable<double> Supplement_Cost_Incl { get; set; }
        public Nullable<int> Supplement_Supplier_ID { get; set; }
        public Nullable<int> Supplement_Min_Levels { get; set; }
        public Nullable<int> Supplement_Stock_Levels { get; set; }
        public string Supplement_Nappi_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Invoice_Supplements> Table_Invoice_Supplements { get; set; }
        public virtual Table_Supplier Table_Supplier { get; set; }
    }
}
