//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_BlogPostKeyword
    {
        public int BlogPostKeywordID { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> BlogPost_ID { get; set; }
        public Nullable<System.DateTime> CapturedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public string Createdby { get; set; }
        public string EditedBy { get; set; }
    
        public virtual Table_BlogPost Table_BlogPost { get; set; }
    }
}
