//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_MedicalCertificate
    {
        public int MedicalCertificateID { get; set; }
        public int Client_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> ConsultedDateTime { get; set; }
        public Nullable<System.DateTime> AdmittedFrom { get; set; }
        public Nullable<System.DateTime> AdmittedTo { get; set; }
        public Nullable<System.DateTime> UnfitSince { get; set; }
        public string NatureOfIllness { get; set; }
        public Nullable<System.DateTime> ResumeDate { get; set; }
        public Nullable<System.DateTime> SignatureDate { get; set; }
        public Nullable<System.DateTime> CapturedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
    
        public virtual Table_ClientData Table_ClientData { get; set; }
    }
}
