//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLogist.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Invoice_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Invoice_Info()
        {
            this.Table_Invoice_Supplements = new HashSet<Table_Invoice_Supplements>();
        }
    
        public int Invoice_Info_ID { get; set; }
        public string Invoice_Number { get; set; }
        public Nullable<int> Invoice_Client_ID { get; set; }
        public Nullable<double> Invoice_Consultation { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<bool> Invoice_Paid { get; set; }
        public string Invoice_Payment_method { get; set; }
        public Nullable<bool> Invoice_Is_Appointment { get; set; }
        public Nullable<bool> Invoice_Is_Supplements { get; set; }
        public Nullable<double> Invoice_Total { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Id_No { get; set; }
        public string EmailAddress { get; set; }
        public string ContactDetails { get; set; }
    
        public virtual Table_ClientData Table_ClientData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Invoice_Supplements> Table_Invoice_Supplements { get; set; }
    }
}
